name: Build Paper
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
#          server-id: heroslender-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
#          server-username: ${{ secrets.nexus_username }} # env variable for username in deploy
#          server-password: ${{ secrets.nexus_password }} # env variable for token in deploy
      - name: Cache maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/
            work/Minecraft
          key: ${{ runner.os }}-paper-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-paper
      - name: Build patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./paper patch
      - name: Build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          mvn clean package
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          server-id: heroslender-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Publish to Maven
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
#          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#      - name: Archive PaperSpigot jar
#        uses: actions/upload-artifact@v2
#        with:
#          name: PaperSpigot-1.8.8.jar
#          path: PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar
#      - name: Create paperclip
#        run: |
#          git config --global user.email "no-reply@github.com"
#          git config --global user.name "Github Actions"
#          ./paper paperclip
#      - name: Archive Paperclip jar
#        uses: actions/upload-artifact@v2
#        with:
#          name: Paperclip-1.8.8.jar
#          path: Paperclip-1.8.8.jar
#      - name: Release Maven package
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
##          gpg_private_key: ${{ secrets.gpg_private_key }}
##          gpg_passphrase: ${{ secrets.gpg_passphrase }}
#          nexus_username: ${{ secrets.nexus_username }}
#          nexus_password: ${{ secrets.nexus_password }}
#          server_id: heroslender-snapshots
##          directory: PaperSpigot-Server
