name: Build Paper
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/
            work/Minecraft
          key: ${{ runner.os }}-paper-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-paper
      - name: Build patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./paper patch
      - name: Build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          mvn clean package
      - name: Archive PaperSpigot jar
        uses: actions/upload-artifact@v2
        with:
          name: PaperSpigot-1.8.8.jar
          path: PaperSpigot-Server/target/paperspigot-1.8.8-R0.1-SNAPSHOT.jar
      - name: Create paperclip
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./paper paperclip
      - name: Archive Paperclip jar
        uses: actions/upload-artifact@v2
        with:
          name: Paperclip-1.8.8.jar
          path: Paperclip-1.8.8.jar
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: ${{ matrix.java }}
          server-id: heroslender-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to Maven
        run: mvn org.apache.maven.plugins:maven-source-plugin:2.1.2:jar-no-fork org.apache.maven.plugins:maven-javadoc-plugin:2.7:jar deploy -DexcludePackageNames="net.minecraft.*" -Dadditionalparam="-Xdoclint:none"
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
